[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#1a1a19"
textColor = "#f2f1ec"
borderColor = "#2c2c2a"
showWidgetBorder = true
baseRadius = "0.5rem"
font = "sans-serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server]
headless = true
